version: 2
defaults: &defaults
  working_directory: ~/circleci-champaign
  docker:
    - image: soutech/ruby2.4.1_node_awscli:0.2
jobs:
  prepare:
    <<: *defaults
    environment:
      EXTERNAL_ASSETS_JS_PATH: /home/circleci/circleci-champaign/tmp/external_assets_source/javascripts/champaign
      EXTERNAL_ASSETS_PATH: /home/circleci/circleci-champaign/tmp/external_assets_source/
    steps:
      - checkout
      - restore_cache:
          name: Restoring bundler cache
          key: gem-cache-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          name: Restoring node_modules cache
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run: bundle install --path vendor/bundle
      - run: yarn --frozen-lockfile
      - run:
          name: Download external assets
          command: bundle exec rake assets:download_external_assets[$EXTERNAL_ASSETS_PATH,$CUSTOM_ASSETS_URL,$CUSTOM_ASSETS_CREDENTIALS,$CIRCLE_BRANCH]
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
          - vendor/bundle
      - run:
          name: Debug yarn cache
          command: |
            ls -lh
            git diff
            git status
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
          - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle
            - node_modules
            - .bundle
            - tmp/external_assets_source
  flow:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - run:
          name: Flow check
          command: yarn run flow check
  jest:
    <<: *defaults
    environment:
      EXTERNAL_ASSETS_JS_PATH: /home/circleci/circleci-champaign/tmp/external_assets_source/javascripts/champaign
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - run:
          name: Run JS tests
          command: yarn run test
  build:
    <<: *defaults
    environment:
      EXTERNAL_ASSETS_PATH: /home/circleci/circleci-champaign/tmp/external_assets_source/
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker build
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            .circleci/build.sh

  precompile_assets:
    # TODO: change epoch in cache key to git commit sha of the last commit in the sou-assets repo
    # (Branch is either current branch, $DEFAULT_ASSET_BRANCH, or 'master', in that order):
    # git ls-remote git://github.com/SumOfUs/sou-assets.git \ grep refs/heads/master | cut -f 1
    <<: *defaults
    environment:
      EXTERNAL_ASSETS_JS_PATH: /home/circleci/circleci-champaign/tmp/external_assets_source/javascripts/champaign
      EXTERNAL_ASSETS_PATH: /home/circleci/circleci-champaign/tmp/external_assets_source/
      RAILS_ENV: production
      NODE_ENV: production
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - run: bundle install --path vendor/bundle
      - run:
          name: Precompile assets
          # NOTE: Webpacker runs yarn on asset precompilation so this will install production assets into node_modules!
          command: bundle exec rake assets:precompile
      - persist_to_workspace:
          root: .
          paths:
            - public

  rspec:
    working_directory: ~/circleci-champaign
    docker:
      - image: soutech/ruby2.4.1_node_awscli:0.2
        environment:
          PG_USERNAME: champaign
          PG_PASSWORD: champaign
          RAILS_ENV: test
          EXTERNAL_ASSETS_JS_PATH: /home/circleci/circleci-champaign/tmp/external_assets_source/javascripts/champaign
          EXTERNAL_ASSETS_PATH: /home/circleci/circleci-champaign/tmp/external_assets_source/
      - image: circleci/postgres:9.4-alpine-ram
        environment:
          POSTGRES_USER: champaign
          POSTGRES_DB: champaign
      - image: redis
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - run:
          name: Migrations and seeding
          command: |
            bundle --path vendor/bundle
            bundle exec rake db:create db:migrate db:seed champaign:seed_liquid
      - run:
          name: Rspec tests
          command: bundle exec rspec spec

  docker_build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker build
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            .circleci/build.sh

  upload_assets_to_production:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - run:
          name: Uploading assets to S3
          command: .circleci/upload_assets.sh 'champaign-assets-production'

  upload_assets_to_staging:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - run:
          name: Uploading assets to S3
          command: .circleci/upload_assets.sh 'champaign-assets-staging'

  upload_assets_to_testing:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - run:
          name: Uploading assets to S3
          command: .circleci/upload_assets.sh 'champaign-assets-testing'

  deploy_production:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - run:
          name: Deploy production
          command: .circleci/deploy.sh $CIRCLE_SHA1 'champaign' 'env-production-1' 'logs3.papertrailapp.com:44107' 'actions.sumofus.org'

  deploy_staging:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - run:
          name: Deploy staging
          command: .circleci/deploy.sh $CIRCLE_SHA1 'champaign' 'env-staging' 'logs3.papertrailapp.com:34848' 'action-staging.sumofus.org'

  deploy_feature:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign
      - run:
          name: Deploy feature branch
          command: .circleci/deploy_testing.sh $CIRCLE_SHA1 'champaign' 'env-feature' 'logs3.papertrailapp.com:34848' 'testing.sumofus.org'


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - prepare
      - flow:
          requires:
            - prepare
      - jest:
          requires:
            - prepare
      - rspec:
          requires:
            - prepare
      - precompile_assets:
          requires:
            - flow
            - jest
      - docker_build:
          requires:
            - rspec
            - precompile_assets
      - upload_assets_to_production:
          requires:
            - precompile_assets
          filters:
            branches:
              only:
                - master
      - upload_assets_to_staging:
          requires:
            - precompile_assets
          filters:
            branches:
              only:
                - circleci-2
      - upload_assets_to_testing:
          requires:
            - precompile_assets
          filters:
            branches:
              only:
                - override
      - deploy_production:
          requires:
            - docker_build
          filters:
            branches:
              only:
                - master
      - deploy_staging:
          requires:
            - docker_build
          filters:
            branches:
              only:
                - circleci-2
      - deploy_feature:
          requires:
            - docker_build
          filters:
            branches:
              only:
                - override
